#!/usr/bin/env python3
"""Reasoning tasks for DAPH-X authority evaluation.

These tasks have NO execution feedback — the authority must decide
based on reasoning features alone. Correctness is verified by
checking the final answer, but there are no "probe tests" to run.

This is the regime where the original DAPH formulation was designed:
the authority must estimate value from the reasoning process, not
from execution evidence.

Task types:
  - Math word problems (verifiable numeric answer)
  - Logic puzzles (verifiable boolean/string answer)
  - Sequence completion (verifiable next element)
  - Combinatorics (verifiable count)
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass
class ReasoningTask:
    task_id: str
    description: str
    prompt: str  # The question to ask the model
    answer: str  # The correct answer (string match)
    answer_type: str  # "int", "float", "string", "bool"
    difficulty: str  # "easy", "medium", "hard"
    category: str  # "math", "logic", "sequence", "combinatorics"
    common_errors: tuple[str, ...]


REASONING_TASKS: list[ReasoningTask] = [
    # ─── Math: arithmetic word problems ───
    ReasoningTask(
        task_id="reason_001",
        description="Train speed problem",
        prompt="A train travels 240 miles in 4 hours. At the same speed, how far will it travel in 7 hours? Answer with just the number.",
        answer="420",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Unit confusion", "Rate calculation error"),
    ),
    ReasoningTask(
        task_id="reason_002",
        description="Percentage problem",
        prompt="A store marks up items by 40% then offers a 25% discount. What percentage of the original price does the customer pay? Answer with just the number.",
        answer="105",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Adding percentages instead of multiplying", "Not computing compound effect"),
    ),
    ReasoningTask(
        task_id="reason_003",
        description="Compound interest",
        prompt="If you invest $1000 at 10% annual interest compounded annually, how much money will you have after 3 years? Answer with just the number (rounded to nearest integer).",
        answer="1331",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Simple interest instead of compound", "Rounding errors"),
    ),
    ReasoningTask(
        task_id="reason_004",
        description="Work rate problem",
        prompt="Alice can paint a room in 6 hours. Bob can paint the same room in 4 hours. Working together, how many hours will it take them to paint the room? Answer with just the number (rounded to 2 decimal places).",
        answer="2.40",
        answer_type="float",
        difficulty="medium",
        category="math",
        common_errors=("Averaging the times", "Not using reciprocal rates"),
    ),
    ReasoningTask(
        task_id="reason_005",
        description="Mixture problem",
        prompt="How many liters of a 20% acid solution must be added to 10 liters of a 50% acid solution to get a 30% acid solution? Answer with just the number.",
        answer="20",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Incorrect equation setup", "Solving for wrong variable"),
    ),
    ReasoningTask(
        task_id="reason_006",
        description="Speed/distance/time",
        prompt="Two cars start 300 miles apart and drive toward each other. One drives 60 mph, the other 40 mph. How long until they meet (in hours)? Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Dividing by one speed", "Not adding speeds"),
    ),
    ReasoningTask(
        task_id="reason_007",
        description="Geometric sequence sum",
        prompt="What is the sum of the first 10 terms of a geometric sequence with first term 3 and common ratio 2? Answer with just the number.",
        answer="3069",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Using arithmetic sum formula", "Off-by-one in term count"),
    ),
    ReasoningTask(
        task_id="reason_008",
        description="Probability problem",
        prompt="A bag contains 5 red marbles and 3 blue marbles. Two marbles are drawn without replacement. What is the probability that both are red? Express as a fraction a/b.",
        answer="5/14",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Not using conditional probability", "Computing with replacement"),
    ),
    ReasoningTask(
        task_id="reason_009",
        description="Integer sequence",
        prompt="What is the next number in the sequence: 2, 6, 12, 20, 30, ?",
        answer="42",
        answer_type="int",
        difficulty="medium",
        category="sequence",
        common_errors=("Arithmetic progression assumption", "Not recognizing n(n+1) pattern"),
    ),
    ReasoningTask(
        task_id="reason_010",
        description="Fibonacci variant",
        prompt="What is the next number in the sequence: 1, 1, 2, 3, 5, 8, 13, ?",
        answer="21",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Arithmetic instead of Fibonacci", "Off-by-one"),
    ),
    ReasoningTask(
        task_id="reason_011",
        description="Geometric sequence",
        prompt="What is the next number in the sequence: 3, 9, 27, 81, ?",
        answer="243",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Adding instead of multiplying", "Wrong ratio"),
    ),
    ReasoningTask(
        task_id="reason_012",
        description="Triangular numbers",
        prompt="What is the next number in the sequence: 1, 3, 6, 10, 15, ?",
        answer="21",
        answer_type="int",
        difficulty="medium",
        category="sequence",
        common_errors=("Arithmetic progression", "Not recognizing triangular pattern"),
    ),
    # ─── Logic puzzles ───
    ReasoningTask(
        task_id="reason_013",
        description="Knights and knaves",
        prompt="On an island, knights always tell the truth and knaves always lie. You meet two people, A and B. A says 'B is a knave.' B says 'We are both knaves.' What is A? Answer 'knight' or 'knave'.",
        answer="knight",
        answer_type="string",
        difficulty="hard",
        category="logic",
        common_errors=("Not checking consistency", "Assuming B tells truth"),
    ),
    ReasoningTask(
        task_id="reason_014",
        description="Syllogism",
        prompt="All cats are mammals. Some mammals are pets. Therefore: (a) all cats are pets, (b) some cats are pets, (c) no cats are pets, (d) none of the above can be concluded. Answer with just the letter.",
        answer="d",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Choosing (b) incorrectly", "Not understanding valid syllogisms"),
    ),
    ReasoningTask(
        task_id="reason_015",
        description="Truth table",
        prompt="If P is true and Q is false, what is the value of (P AND Q) OR (NOT Q)? Answer 'true' or 'false'.",
        answer="true",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Evaluating AND first incorrectly", "NOT operator error"),
    ),
    ReasoningTask(
        task_id="reason_016",
        description="Conditional logic",
        prompt="If it rains, the picnic is cancelled. The picnic was not cancelled. Did it rain? Answer 'yes', 'no', or 'cannot determine'.",
        answer="no",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Affirming the consequent", "Confusing contrapositive"),
    ),
    # ─── Combinatorics ───
    ReasoningTask(
        task_id="reason_017",
        description="Permutations",
        prompt="How many ways can 5 books be arranged on a shelf? Answer with just the number.",
        answer="120",
        answer_type="int",
        difficulty="easy",
        category="combinatorics",
        common_errors=("Computing combinations instead", "Not using factorial"),
    ),
    ReasoningTask(
        task_id="reason_018",
        description="Combinations",
        prompt="How many ways can you choose 3 items from 7 items? Answer with just the number.",
        answer="35",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Using permutation formula", "Arithmetic error in C(7,3)"),
    ),
    ReasoningTask(
        task_id="reason_019",
        description="Stars and bars",
        prompt="How many ways can you distribute 10 identical candies among 3 children? Answer with just the number.",
        answer="66",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using stars and bars", "Treating candies as distinct"),
    ),
    ReasoningTask(
        task_id="reason_020",
        description="Derangements",
        prompt="How many derangements (permutations where no element is in its original position) are there of 4 elements? Answer with just the number.",
        answer="9",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not knowing derangement formula", "Computing permutations instead"),
    ),
    # ─── More math ───
    ReasoningTask(
        task_id="reason_021",
        description="Modular arithmetic",
        prompt="What is 7^100 mod 11? Answer with just the number.",
        answer="1",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not using Fermat's little theorem", "Direct computation overflow"),
    ),
    ReasoningTask(
        task_id="reason_022",
        description="Number theory",
        prompt="What is the GCD of 1071 and 462? Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using Euclidean algorithm", "Arithmetic errors"),
    ),
    ReasoningTask(
        task_id="reason_023",
        description="Algebra",
        prompt="If x^2 - 5x + 6 = 0, what is the sum of all possible values of x? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Solving for x instead of using Vieta's", "Not recognizing both roots"),
    ),
    ReasoningTask(
        task_id="reason_024",
        description="Inequality",
        prompt="For what value of x is |2x - 3| = 7? If there are two solutions, give the larger one. Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Only finding one solution", "Sign error in absolute value"),
    ),
    ReasoningTask(
        task_id="reason_025",
        description="Logarithm",
        prompt="If log_2(x) = 10, what is x? Answer with just the number.",
        answer="1024",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Computing log instead of exponential", "Base confusion"),
    ),
    ReasoningTask(
        task_id="reason_026",
        description="Sum of arithmetic series",
        prompt="What is the sum of all integers from 1 to 100? Answer with just the number.",
        answer="5050",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not using n(n+1)/2", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_027",
        description="Pythagorean theorem",
        prompt="A right triangle has legs of length 5 and 12. What is the length of the hypotenuse? Answer with just the number.",
        answer="13",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Adding legs instead of sqrt(a^2+b^2)", "Computation error"),
    ),
    ReasoningTask(
        task_id="reason_028",
        description="Area problem",
        prompt="A circle has radius 6. What is its area? Use pi = 3.14. Answer with just the number.",
        answer="113.04",
        answer_type="float",
        difficulty="easy",
        category="math",
        common_errors=("Using diameter instead of radius", "Not squaring radius"),
    ),
    ReasoningTask(
        task_id="reason_029",
        description="Ratio problem",
        prompt="The ratio of boys to girls in a class is 3:2. If there are 10 girls, how many boys are there? Answer with just the number.",
        answer="15",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Inverting the ratio", "Not scaling properly"),
    ),
    ReasoningTask(
        task_id="reason_030",
        description="Age problem",
        prompt="Tom is currently twice as old as Jerry. Ten years ago, Tom was three times as old as Jerry. How old is Tom now? Answer with just the number.",
        answer="40",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Setting up wrong equations", "Solving for wrong variable"),
    ),
    ReasoningTask(
        task_id="reason_031",
        description="Digit sum",
        prompt="What is the digit sum of 2^20? Answer with just the number.",
        answer="31",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Computing 2^20 incorrectly", "Digit sum arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_032",
        description="Remainder problem",
        prompt="What is the remainder when 100! is divided by 97? Answer with just the number.",
        answer="0",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not recognizing 97 is a factor of 100!", "Trying to compute 100! directly"),
    ),
    ReasoningTask(
        task_id="reason_033",
        description="Average speed",
        prompt="A car travels 60 miles at 30 mph and returns 60 miles at 60 mph. What is the average speed for the entire trip? Answer with just the number (rounded to 1 decimal place).",
        answer="40.0",
        answer_type="float",
        difficulty="medium",
        category="math",
        common_errors=("Averaging the speeds (45)", "Not using harmonic mean"),
    ),
    ReasoningTask(
        task_id="reason_034",
        description="LCM problem",
        prompt="What is the LCM of 12, 15, and 20? Answer with just the number.",
        answer="60",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Computing GCD instead", "Not factoring all three"),
    ),
    ReasoningTask(
        task_id="reason_035",
        description="Telescoping series",
        prompt="What is 1/(1*2) + 1/(2*3) + 1/(3*4) + ... + 1/(99*100)? Answer as a decimal.",
        answer="0.99",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not recognizing telescoping pattern", "Computing each term individually"),
    ),
    ReasoningTask(
        task_id="reason_036",
        description="Clock angle",
        prompt="What is the angle between the hour and minute hands of a clock at 3:15? Answer with just the number (in degrees).",
        answer="7.5",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Saying 0 degrees", "Not accounting for hour hand movement"),
    ),
    ReasoningTask(
        task_id="reason_037",
        description="Coin problem",
        prompt="What is the minimum number of coins needed to make 67 cents using quarters (25c), dimes (10c), nickels (5c), and pennies (1c)? Answer with just the number.",
        answer="6",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Greedy doesn't always work (but does for US coins)", "Counting error"),
    ),
    ReasoningTask(
        task_id="reason_038",
        description="Pascal's triangle",
        prompt="What is the value in the 5th row and 3rd position (0-indexed) of Pascal's triangle? Answer with just the number.",
        answer="10",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("1-indexed vs 0-indexed confusion", "Wrong row/column"),
    ),
    ReasoningTask(
        task_id="reason_039",
        description="Euler's formula",
        prompt="A polyhedron has 8 vertices and 12 edges. How many faces does it have? Answer with just the number.",
        answer="6",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not knowing V-E+F=2", "Wrong sign"),
    ),
    ReasoningTask(
        task_id="reason_040",
        description="Sum of squares",
        prompt="What is 1^2 + 2^2 + 3^2 + ... + 10^2? Answer with just the number.",
        answer="385",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Using n(n+1)/2 instead of n(n+1)(2n+1)/6", "Arithmetic error"),
    ),
    # ─── More logic ───
    ReasoningTask(
        task_id="reason_041",
        description="Conditional with contrapositive",
        prompt="If all Bloops are Razzies and all Razzies are Lazzies, then are all Bloops definitely Lazzies? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Not recognizing transitivity", "Overthinking"),
    ),
    ReasoningTask(
        task_id="reason_042",
        description="Set theory",
        prompt="In a class of 30 students, 18 like math and 15 like science. If 8 like both, how many like neither? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="medium",
        category="logic",
        common_errors=("Not using inclusion-exclusion", "Subtracting both instead of intersection"),
    ),
    ReasoningTask(
        task_id="reason_043",
        description="Truth teller puzzle",
        prompt="Three friends — Alex, Bob, and Carl — are standing in a line. Alex says 'Bob is lying.' Bob says 'Carl is lying.' Carl says 'Alex and Bob are both lying.' Who is telling the truth? Answer with the name.",
        answer="Bob",
        answer_type="string",
        difficulty="hard",
        category="logic",
        common_errors=("Not checking all combinations", "Inconsistent reasoning"),
    ),
    ReasoningTask(
        task_id="reason_044",
        description="River crossing",
        prompt="A farmer needs to cross a river with a fox, a chicken, and a bag of grain. The boat can carry the farmer and one item. The fox eats the chicken if left alone; the chicken eats the grain if left alone. What is the minimum number of crossings needed? Answer with just the number.",
        answer="7",
        answer_type="int",
        difficulty="hard",
        category="logic",
        common_errors=("Not bringing the chicken back", "Counting one-way trips only"),
    ),
    ReasoningTask(
        task_id="reason_045",
        description="Bertrand box",
        prompt="There are 3 boxes: one with 2 gold coins, one with 2 silver coins, and one with 1 gold and 1 silver. You pick a random box and draw a gold coin. What is the probability the next coin from the same box is also gold? Answer as a fraction a/b.",
        answer="2/3",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Saying 1/2 (conditional probability error)", "Not counting all gold coin scenarios"),
    ),
    # ─── More sequences ───
    ReasoningTask(
        task_id="reason_046",
        description="Square numbers",
        prompt="What is the next number in the sequence: 1, 4, 9, 16, 25, ?",
        answer="36",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Arithmetic progression", "Not recognizing squares"),
    ),
    ReasoningTask(
        task_id="reason_047",
        description="Cube sequence",
        prompt="What is the next number in the sequence: 1, 8, 27, 64, ?",
        answer="125",
        answer_type="int",
        difficulty="medium",
        category="sequence",
        common_errors=("Arithmetic progression", "Not recognizing cubes"),
    ),
    ReasoningTask(
        task_id="reason_048",
        description="Powers of 2",
        prompt="What is the next number in the sequence: 1, 2, 4, 8, 16, 32, ?",
        answer="64",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Adding instead of doubling", "Off-by-one"),
    ),
    ReasoningTask(
        task_id="reason_049",
        description="Lucas numbers",
        prompt="What is the next number in the sequence: 2, 1, 3, 4, 7, 11, ?",
        answer="18",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing Lucas pattern", "Arithmetic assumption"),
    ),
    ReasoningTask(
        task_id="reason_050",
        description="Pentagonal numbers",
        prompt="What is the next number in the sequence: 1, 5, 12, 22, 35, ?",
        answer="51",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing pentagonal pattern", "Wrong difference calculation"),
    ),
    # ─── More combinatorics ───
    ReasoningTask(
        task_id="reason_051",
        description="Circular permutations",
        prompt="How many ways can 6 people be seated around a circular table? Answer with just the number.",
        answer="120",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not dividing by n for circular", "Using 6! instead of 5!"),
    ),
    ReasoningTask(
        task_id="reason_052",
        description="Binomial coefficient",
        prompt="What is C(10,4)? Answer with just the number.",
        answer="210",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Arithmetic error", "Using P(10,4) instead"),
    ),
    ReasoningTask(
        task_id="reason_053",
        description="Inclusion-exclusion",
        prompt="In a group of 50 people, 25 speak English, 20 speak French, and 10 speak both. How many speak neither? Answer with just the number.",
        answer="15",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Not using inclusion-exclusion", "Adding instead of subtracting intersection"),
    ),
    ReasoningTask(
        task_id="reason_054",
        description="Stars and bars variant",
        prompt="How many non-negative integer solutions are there to x + y + z = 8? Answer with just the number.",
        answer="45",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using C(10,2)", "Counting manually"),
    ),
    ReasoningTask(
        task_id="reason_055",
        description="Catalan number",
        prompt="What is the 4th Catalan number (0-indexed)? Answer with just the number.",
        answer="14",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not knowing Catalan formula", "1-indexed vs 0-indexed"),
    ),
    # ─── Advanced math ───
    ReasoningTask(
        task_id="reason_056",
        description="Sum of divisors",
        prompt="What is the sum of all positive divisors of 28? Answer with just the number.",
        answer="56",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Missing divisors", "Including 28 twice"),
    ),
    ReasoningTask(
        task_id="reason_057",
        description="Perfect number check",
        prompt="Is 496 a perfect number (sum of proper divisors equals the number)? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not computing all divisors", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_058",
        description="Prime counting",
        prompt="How many prime numbers are there between 1 and 20? Answer with just the number.",
        answer="8",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Including 1 as prime", "Missing a prime"),
    ),
    ReasoningTask(
        task_id="reason_059",
        description="Euler totient",
        prompt="What is Euler's totient function phi(12) (count of integers 1-12 coprime to 12)? Answer with just the number.",
        answer="4",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not knowing totient formula", "Counting non-coprime instead"),
    ),
    ReasoningTask(
        task_id="reason_060",
        description="Matrix determinant",
        prompt="What is the determinant of the 2x2 matrix [[3, 4], [2, 5]]? Answer with just the number.",
        answer="7",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Wrong formula (ad+bc instead of ad-bc)", "Sign error"),
    ),
    # ─── Batch 2: tasks 061-120 ───
    # More math
    ReasoningTask(
        task_id="reason_061",
        description="Harmonic mean",
        prompt="Two numbers have arithmetic mean 10 and geometric mean 8. What is their harmonic mean? Answer with just the number (rounded to 2 decimal places).",
        answer="6.40",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not knowing HM = GM^2/AM", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_062",
        description="Sum of geometric series",
        prompt="What is the sum of 1 + 1/2 + 1/4 + 1/8 + ... (infinite series)? Answer as a decimal.",
        answer="2",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using a/(1-r)", "Saying infinity"),
    ),
    ReasoningTask(
        task_id="reason_063",
        description="Binomial expansion coefficient",
        prompt="What is the coefficient of x^3 in the expansion of (1+x)^6? Answer with just the number.",
        answer="20",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Using C(6,2) instead of C(6,3)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_064",
        description="Modular exponentiation",
        prompt="What is 3^7 mod 7? Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not using Fermat's little theorem", "Direct computation error"),
    ),
    ReasoningTask(
        task_id="reason_065",
        description="System of equations",
        prompt="If 2x + 3y = 12 and x - y = 1, what is x + y? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Solving for individual variables incorrectly", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_066",
        description="Probability of dice sum",
        prompt="Two fair dice are rolled. What is the probability that the sum is 7? Express as a fraction a/b.",
        answer="1/6",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Counting 5/36 instead of 6/36", "Not enumerating all pairs"),
    ),
    ReasoningTask(
        task_id="reason_067",
        description="Expected value",
        prompt="A fair die is rolled once. What is the expected value of the outcome? Answer with just the number.",
        answer="3.5",
        answer_type="float",
        difficulty="easy",
        category="math",
        common_errors=("Saying 3 (integer)", "Not averaging all outcomes"),
    ),
    ReasoningTask(
        task_id="reason_068",
        description="Birthday problem approximation",
        prompt="In a group of 23 people, what is the approximate probability that at least two share a birthday? Answer as a percentage rounded to the nearest integer.",
        answer="51",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Saying very low probability", "Not using complement"),
    ),
    ReasoningTask(
        task_id="reason_069",
        description="Sum of angles in polygon",
        prompt="What is the sum of interior angles of a hexagon (in degrees)? Answer with just the number.",
        answer="720",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Using (n-2)*180 with wrong n", "Saying 360"),
    ),
    ReasoningTask(
        task_id="reason_070",
        description="Surface area of cube",
        prompt="A cube has edge length 4. What is its surface area? Answer with just the number.",
        answer="96",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Computing volume instead", "Not multiplying by 6 faces"),
    ),
    ReasoningTask(
        task_id="reason_071",
        description="Volume of sphere",
        prompt="A sphere has radius 3. What is its volume? Use pi = 3.14. Answer with just the number (rounded to 2 decimal places).",
        answer="113.04",
        answer_type="float",
        difficulty="medium",
        category="math",
        common_errors=("Using 4/3 * pi * r^2 instead of r^3", "Diameter vs radius"),
    ),
    ReasoningTask(
        task_id="reason_072",
        description="Arithmetic mean of consecutive integers",
        prompt="What is the arithmetic mean of all integers from 1 to 99? Answer with just the number.",
        answer="50",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Computing sum/count incorrectly", "Saying 49.5"),
    ),
    ReasoningTask(
        task_id="reason_073",
        description="Probability with replacement",
        prompt="A bag has 4 red and 6 blue marbles. Two are drawn WITH replacement. What is the probability both are blue? Express as a fraction a/b.",
        answer="9/25",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Using without replacement", "Not squaring 6/10"),
    ),
    ReasoningTask(
        task_id="reason_074",
        description="Chinese remainder theorem",
        prompt="What is the smallest positive integer that leaves remainder 2 when divided by 3 and remainder 3 when divided by 5? Answer with just the number.",
        answer="8",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not checking both conditions", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_075",
        description="Sum of cubes",
        prompt="What is 1^3 + 2^3 + 3^3 + 4^3 + 5^3? Answer with just the number.",
        answer="225",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Using wrong formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_076",
        description="Inverse proportion",
        prompt="If 6 workers can build a wall in 10 days, how many days will it take 15 workers? Answer with just the number.",
        answer="4",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Direct proportion (15/6*10)", "Not inverting ratio"),
    ),
    ReasoningTask(
        task_id="reason_077",
        description="Quadratic discriminant",
        prompt="For the quadratic equation 3x^2 - 7x + 2 = 0, what is the discriminant? Answer with just the number.",
        answer="25",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Using b^2-4ac with wrong signs", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_078",
        description="Sum of divisors of prime",
        prompt="What is the sum of all positive divisors of 17? Answer with just the number.",
        answer="18",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Forgetting 1", "Forgetting the number itself"),
    ),
    ReasoningTask(
        task_id="reason_079",
        description="Bayes theorem",
        prompt="A disease affects 1% of the population. A test is 90% sensitive and 80% specific. If you test positive, what is the probability you have the disease? Answer as a percentage rounded to the nearest integer.",
        answer="4",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Saying 90%", "Not using Bayes' theorem"),
    ),
    ReasoningTask(
        task_id="reason_080",
        description="Geometric mean",
        prompt="What is the geometric mean of 4 and 16? Answer with just the number.",
        answer="8",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Arithmetic mean instead", "Not using sqrt(a*b)"),
    ),
    # More logic
    ReasoningTask(
        task_id="reason_081",
        description="Euler's identity check",
        prompt="Is e^(i*pi) + 1 = 0? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not recognizing Euler's identity", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_082",
        description="Pigeonhole principle",
        prompt="In a drawer with 10 red socks and 10 blue socks, what is the minimum number of socks you must pull out to guarantee a matching pair? Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="easy",
        category="logic",
        common_errors=("Saying 2", "Not using pigeonhole"),
    ),
    ReasoningTask(
        task_id="reason_083",
        description="Two envelopes paradox check",
        prompt="If one envelope contains twice as much as the other, and you pick one at random, is switching beneficial? Answer 'yes', 'no', or 'cannot determine'.",
        answer="no",
        answer_type="string",
        difficulty="hard",
        category="logic",
        common_errors=("Saying yes (paradoxical reasoning)", "Not recognizing symmetry"),
    ),
    ReasoningTask(
        task_id="reason_084",
        description="Logical equivalence",
        prompt="Is 'not (P and Q)' logically equivalent to '(not P) or (not Q)'? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not recognizing De Morgan's law", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_085",
        description="Contrapositive",
        prompt="The contrapositive of 'If P then Q' is 'If not Q then not P'. Is the contrapositive always logically equivalent to the original? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Saying no", "Confusing with converse"),
    ),
    ReasoningTask(
        task_id="reason_086",
        description="Light switch puzzle",
        prompt="Three light switches control three bulbs in another room. You can only enter the room once. How many switches do you need to toggle to determine which switch controls which bulb? Answer with just the number.",
        answer="2",
        answer_type="int",
        difficulty="hard",
        category="logic",
        common_errors=("Saying 3", "Not using heat from incandescent bulbs"),
    ),
    ReasoningTask(
        task_id="reason_087",
        description="Monty Hall problem",
        prompt="In the Monty Hall problem, you pick door 1. The host opens door 3 to reveal a goat. Should you switch to door 2? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="hard",
        category="logic",
        common_errors=("Saying no (50-50 fallacy)", "Not accounting for host knowledge"),
    ),
    ReasoningTask(
        task_id="reason_088",
        description="Hat puzzle",
        prompt="Three prisoners wear hats that are either red or blue. Each can see the others' hats but not their own. They can all see at least one red hat. If the first prisoner says 'I don't know my hat color', what can the second prisoner deduce? Answer 'red', 'blue', or 'cannot determine'.",
        answer="cannot determine",
        answer_type="string",
        difficulty="hard",
        category="logic",
        common_errors=("Saying red or blue", "Not reasoning through all cases"),
    ),
    ReasoningTask(
        task_id="reason_089",
        description="Boolean algebra",
        prompt="Simplify: A AND (A OR B). Answer with just the simplified expression (use AND, OR, NOT, variables).",
        answer="A",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Saying A AND B", "Not applying absorption law"),
    ),
    ReasoningTask(
        task_id="reason_090",
        description="Transitive reasoning",
        prompt="Alice is taller than Bob. Bob is taller than Carol. Carol is taller than Dave. Is Alice taller than Dave? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Overthinking", "Not recognizing transitivity"),
    ),
    # More sequences
    ReasoningTask(
        task_id="reason_091",
        description="Tribonacci sequence",
        prompt="What is the next number in the sequence: 0, 1, 1, 2, 4, 7, 13, ?",
        answer="24",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing sum of 3 previous", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_092",
        description="Powers of 3",
        prompt="What is the next number in the sequence: 1, 3, 9, 27, 81, ?",
        answer="243",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Adding instead of multiplying", "Wrong ratio"),
    ),
    ReasoningTask(
        task_id="reason_093",
        description="Alternating add/multiply",
        prompt="What is the next number in the sequence: 1, 2, 4, 8, 16, 32, 64, ?",
        answer="128",
        answer_type="int",
        difficulty="easy",
        category="sequence",
        common_errors=("Not recognizing powers of 2", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_094",
        description="Look-and-say sequence",
        prompt="What is the next term in the look-and-say sequence: 1, 11, 21, 1211, 111221, ?",
        answer="312211",
        answer_type="string",
        difficulty="hard",
        category="sequence",
        common_errors=("Not understanding look-and-say rule", "Arithmetic approach"),
    ),
    ReasoningTask(
        task_id="reason_095",
        description="Hexagonal numbers",
        prompt="What is the next number in the sequence: 1, 6, 15, 28, 45, ?",
        answer="66",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing hexagonal pattern", "Wrong difference"),
    ),
    ReasoningTask(
        task_id="reason_096",
        description="Factorial sequence",
        prompt="What is the next number in the sequence: 1, 2, 6, 24, 120, ?",
        answer="720",
        answer_type="int",
        difficulty="medium",
        category="sequence",
        common_errors=("Not recognizing factorials", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_097",
        description="Double factorial",
        prompt="What is the next number in the sequence: 1, 3, 15, 105, 945, ?",
        answer="10395",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing odd double factorials", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_098",
        description="Padovan sequence",
        prompt="What is the next number in the sequence: 1, 1, 1, 2, 2, 3, 4, 5, 7, 9, ?",
        answer="12",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing P(n)=P(n-2)+P(n-3)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_099",
        description="Recaman sequence start",
        prompt="What is the next number in the sequence: 0, 1, 3, 6, 2, 7, 13, 20, 12, ?",
        answer="21",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not knowing Recaman rule", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_100",
        description="Collatz steps",
        prompt="Starting with 6, how many steps does it take to reach 1 in the Collatz sequence (if even, divide by 2; if odd, multiply by 3 and add 1)? Answer with just the number.",
        answer="8",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Miscounting steps", "Not following the sequence correctly"),
    ),
    # More combinatorics
    ReasoningTask(
        task_id="reason_101",
        description="Multiset coefficient",
        prompt="How many ways can you distribute 7 identical balls into 4 distinct boxes? Answer with just the number.",
        answer="120",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using C(10,3)", "Treating balls as distinct"),
    ),
    ReasoningTask(
        task_id="reason_102",
        description="Stirling number approximation",
        prompt="How many ways to partition a set of 4 elements into 2 non-empty subsets? Answer with just the number.",
        answer="7",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not knowing Stirling numbers", "Saying 6"),
    ),
    ReasoningTask(
        task_id="reason_103",
        description="Permutation with repetition",
        prompt="How many distinct arrangements of the letters in MISSISSIPPI are there? Answer with just the number.",
        answer="34650",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not accounting for repeated letters", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_104",
        description="Pigeonhole with socks",
        prompt="In a drawer with socks of 5 different colors, what is the minimum number of socks you must pull out to guarantee at least 4 of the same color? Answer with just the number.",
        answer="16",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Saying 15", "Not using pigeonhole correctly"),
    ),
    ReasoningTask(
        task_id="reason_105",
        description="Bell number",
        prompt="How many ways can a set of 3 elements be partitioned into non-empty subsets? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not knowing Bell numbers", "Saying 4"),
    ),
    ReasoningTask(
        task_id="reason_106",
        description="Inclusion-exclusion three sets",
        prompt="In a survey: 60% like tea, 50% like coffee, 40% like milk. 20% like tea and coffee, 15% like coffee and milk, 10% like tea and milk. 5% like all three. What percentage like at least one? Answer with just the number.",
        answer="110",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using three-set inclusion-exclusion", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_107",
        description="Derangement of 5",
        prompt="How many derangements of 5 elements are there? Answer with just the number.",
        answer="44",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using derangement formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_108",
        description="Lattice paths",
        prompt="How many ways can you walk from (0,0) to (3,3) on a grid, moving only right or up? Answer with just the number.",
        answer="20",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Not using C(6,3)", "Counting paths manually"),
    ),
    ReasoningTask(
        task_id="reason_109",
        description="Multinomial coefficient",
        prompt="How many ways can you arrange 6 people in a line if 3 must be together as a block? Answer with just the number.",
        answer="144",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not treating block as one unit", "Not multiplying by 3!"),
    ),
    ReasoningTask(
        task_id="reason_110",
        description="Generating function coefficient",
        prompt="In the expansion of (1+x+x^2)^4, what is the coefficient of x^3? Answer with just the number.",
        answer="10",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using multinomial", "Arithmetic error"),
    ),
    # More advanced math
    ReasoningTask(
        task_id="reason_111",
        description="Sum of alternating series",
        prompt="What is 1 - 1/2 + 1/3 - 1/4 + 1/5 - ... (infinite alternating series)? Answer as a decimal rounded to 3 decimal places.",
        answer="0.693",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not recognizing ln(2)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_112",
        description="Taylor series",
        prompt="What is the Taylor series expansion of e^x around 0, evaluated at x=1, to 3 terms? Answer as a decimal rounded to 3 decimal places.",
        answer="2.667",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not using 1 + x + x^2/2", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_113",
        description="Integration",
        prompt="What is the integral of x^2 from 0 to 3? Answer with just the number.",
        answer="9",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using x^3/3", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_114",
        description="Derivative",
        prompt="What is the derivative of 3x^3 - 2x^2 + 5x - 1 evaluated at x=2? Answer with just the number.",
        answer="33",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Wrong derivative", "Evaluation error"),
    ),
    ReasoningTask(
        task_id="reason_115",
        description="Limit",
        prompt="What is the limit of (x^2 - 1)/(x - 1) as x approaches 1? Answer with just the number.",
        answer="2",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Saying 0/0", "Not factoring numerator"),
    ),
    ReasoningTask(
        task_id="reason_116",
        description="Complex number modulus",
        prompt="What is the modulus of the complex number 3 + 4i? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using sqrt(a^2+b^2)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_117",
        description="Trigonometric value",
        prompt="What is sin(30 degrees)? Answer as a decimal.",
        answer="0.5",
        answer_type="float",
        difficulty="easy",
        category="math",
        common_errors=("Using radians instead of degrees", "Saying 0.866"),
    ),
    ReasoningTask(
        task_id="reason_118",
        description="Logarithm property",
        prompt="What is log_2(8) + log_2(4)? Answer with just the number.",
        answer="5",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Multiplying instead of adding logs", "Wrong base"),
    ),
    ReasoningTask(
        task_id="reason_119",
        description="Arithmetic progression sum",
        prompt="What is the sum of the arithmetic series 5 + 8 + 11 + 14 + ... (20 terms)? Answer with just the number.",
        answer="670",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Wrong formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_120",
        description="Geometric progression product",
        prompt="What is the product of the first 5 powers of 2: 2^1 * 2^2 * 2^3 * 2^4 * 2^5? Answer with just the number.",
        answer="32768",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Adding exponents instead of multiplying", "Arithmetic error"),
    ),
    # ─── Batch 3: tasks 121-200 ───
    ReasoningTask(
        task_id="reason_121",
        description="Sum of arithmetic series with negative",
        prompt="What is the sum of the arithmetic series -3 + (-1) + 1 + 3 + ... + 97? Answer with just the number.",
        answer="2350",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Wrong number of terms", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_122",
        description="Probability of at least one",
        prompt="A die is rolled 3 times. What is the probability of getting at least one 6? Express as a decimal rounded to 3 places.",
        answer="0.421",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not using complement", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_123",
        description="Tetrahedron faces",
        prompt="How many faces does a tetrahedron have? Answer with just the number.",
        answer="4",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Confusing with other polyhedra", "Saying 6"),
    ),
    ReasoningTask(
        task_id="reason_124",
        description="Octahedron vertices",
        prompt="How many vertices does an octahedron have? Answer with just the number.",
        answer="6",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Saying 8", "Confusing vertices with faces"),
    ),
    ReasoningTask(
        task_id="reason_125",
        description="Dodecahedron edges",
        prompt="How many edges does a dodecahedron have? Answer with just the number.",
        answer="30",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not using Euler's formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_126",
        description="Sum of first n odd numbers",
        prompt="What is the sum of the first 50 odd positive integers? Answer with just the number.",
        answer="2500",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using n^2 formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_127",
        description="Difference of squares",
        prompt="What is 99^2 - 1^2? Answer with just the number.",
        answer="9800",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Computing 99^2 directly", "Not using (a-b)(a+b)"),
    ),
    ReasoningTask(
        task_id="reason_128",
        description="Sum of geometric series ratio < 1",
        prompt="What is 8 + 4 + 2 + 1 + 0.5 + 0.25 + ... (infinite)? Answer as a decimal.",
        answer="16",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using a/(1-r)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_129",
        description="Conditional probability with table",
        prompt="In a group, 40% are men and 60% are women. 10% of men and 5% of women are left-handed. What percentage of left-handed people are men? Answer with just the number.",
        answer="57",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not using Bayes", "Computing P(left|men) instead"),
    ),
    ReasoningTask(
        task_id="reason_130",
        description="Expected value of dice game",
        prompt="You roll a die. If it shows 6, you win $5. Otherwise, you lose $1. What is your expected value? Answer with just the number (include sign).",
        answer="0",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not computing (5-5)/6", "Sign error"),
    ),
    ReasoningTask(
        task_id="reason_131",
        description="Harmonic progression check",
        prompt="Is 1/2, 1/4, 1/6, 1/8 a harmonic progression? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="hard",
        category="sequence",
        common_errors=("Not checking reciprocals form AP", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_132",
        description="Arithmetic-geometric sequence",
        prompt="What is the next number in the sequence: 2, 5, 10, 17, 26, 37, ?",
        answer="50",
        answer_type="int",
        difficulty="medium",
        category="sequence",
        common_errors=("Not recognizing n^2+1 pattern", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_133",
        description="Fibonacci ratio",
        prompt="What is the limit of F(n+1)/F(n) as n approaches infinity, where F is the Fibonacci sequence? Answer as a decimal rounded to 3 places.",
        answer="1.618",
        answer_type="float",
        difficulty="hard",
        category="sequence",
        common_errors=("Not knowing golden ratio", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_134",
        description="Sum of alternating harmonic",
        prompt="What is 1 - 1/3 + 1/5 - 1/7 + 1/9 - ... (infinite)? Answer as a decimal rounded to 3 places.",
        answer="0.785",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not recognizing pi/4", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_135",
        description="Newton's method approximation",
        prompt="Using Newton's method starting at x=2, what is the first approximation to sqrt(5)? Answer as a decimal rounded to 3 places.",
        answer="2.250",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Wrong formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_136",
        description="Sum of divisors of perfect square",
        prompt="What is the sum of all positive divisors of 36? Answer with just the number.",
        answer="91",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Missing divisors", "Counting 36 twice"),
    ),
    ReasoningTask(
        task_id="reason_137",
        description="Number of positive divisors",
        prompt="How many positive divisors does 360 have? Answer with just the number.",
        answer="24",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not factoring properly", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_138",
        description="Euler totient of prime power",
        prompt="What is Euler's totient function phi(49)? Answer with just the number.",
        answer="42",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not using p^k - p^(k-1)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_139",
        description="Wilson's theorem check",
        prompt="Is (p-1)! ≡ -1 (mod p) true for all primes p? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not knowing Wilson's theorem", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_140",
        description="Goldbach conjecture check",
        prompt="Can every even integer greater than 2 be expressed as the sum of two primes? Answer 'yes', 'no', or 'unproven'.",
        answer="unproven",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Saying yes (it's unproven)", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_141",
        description="Continuity check",
        prompt="Is f(x) = |x| continuous at x=0? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="math",
        common_errors=("Confusing continuity with differentiability", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_142",
        description="Differentiability check",
        prompt="Is f(x) = |x| differentiable at x=0? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="easy",
        category="math",
        common_errors=("Confusing with continuity", "Saying yes"),
    ),
    ReasoningTask(
        task_id="reason_143",
        description="L'Hopital's rule",
        prompt="What is the limit of sin(x)/x as x approaches 0? Answer with just the number.",
        answer="1",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Saying 0/0", "Not knowing the limit"),
    ),
    ReasoningTask(
        task_id="reason_144",
        description="Chain rule derivative",
        prompt="What is the derivative of sin(x^2) with respect to x? Express your answer using cos and x. Do not use spaces.",
        answer="2*x*cos(x^2)",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Forgetting chain rule", "Wrong inner derivative"),
    ),
    ReasoningTask(
        task_id="reason_145",
        description="Integration by parts",
        prompt="What is the integral of x * e^x dx? Express your answer using x and e. Do not use spaces. Do not include +C.",
        answer="x*e^x-e^x",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not using integration by parts", "Wrong sign"),
    ),
    ReasoningTask(
        task_id="reason_146",
        description="Matrix multiplication",
        prompt="What is the product of matrices [[1,2],[3,4]] and [[5,6],[7,8]]? Give the top-left element. Answer with just the number.",
        answer="19",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Wrong matrix multiplication", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_147",
        description="Eigenvalue of 2x2",
        prompt="What are the eigenvalues of the matrix [[2,0],[0,3]]? Give the larger one. Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not recognizing diagonal matrix", "Saying 2"),
    ),
    ReasoningTask(
        task_id="reason_148",
        description="Trace of matrix",
        prompt="What is the trace of the matrix [[1,2,3],[4,5,6],[7,8,9]]? Answer with just the number.",
        answer="15",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not summing diagonal", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_149",
        description="Inverse matrix element",
        prompt="What is the (1,1) element of the inverse of [[2,0],[0,3]]? Answer as a decimal.",
        answer="0.5",
        answer_type="float",
        difficulty="medium",
        category="math",
        common_errors=("Not inverting correctly", "Saying 2"),
    ),
    ReasoningTask(
        task_id="reason_150",
        description="Vector dot product",
        prompt="What is the dot product of vectors (1,2,3) and (4,5,6)? Answer with just the number.",
        answer="32",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not multiplying component-wise", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_151",
        description="Cross product magnitude",
        prompt="What is the magnitude of the cross product of vectors (1,0,0) and (0,1,0)? Answer with just the number.",
        answer="1",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not knowing cross product", "Saying 0"),
    ),
    ReasoningTask(
        task_id="reason_152",
        description="Vector perpendicularity",
        prompt="Are vectors (1,2) and (-2,1) perpendicular? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Not checking dot product = 0", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_153",
        description="Probability of flush",
        prompt="In 5-card poker from a standard 52-card deck, what is the probability of a flush (all same suit)? Express as a decimal rounded to 4 places.",
        answer="0.00198",
        answer_type="float",
        difficulty="hard",
        category="math",
        common_errors=("Not using combinations", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_154",
        description="Expected rolls for first 6",
        prompt="How many times do you expect to roll a die until you get a 6? Answer with just the number.",
        answer="6",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using 1/p", "Saying 3"),
    ),
    ReasoningTask(
        task_id="reason_155",
        description="Variance of fair die",
        prompt="What is the variance of a fair six-sided die? Answer as a fraction a/b.",
        answer="35/12",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not computing E[X^2]-E[X]^2", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_156",
        description="Chebyshev bound",
        prompt="For a random variable with mean 10 and variance 4, what is the maximum probability that |X-10| >= 6? Answer as a fraction a/b.",
        answer="1/9",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not using Chebyshev: P >= k^2/sigma^2", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_157",
        description="Markov inequality",
        prompt="For a non-negative random variable with mean 5, what is the maximum probability that X >= 15? Answer as a fraction a/b.",
        answer="1/3",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not using Markov: P(X>=a) <= E[X]/a", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_158",
        description="Series convergence",
        prompt="Does the series sum of 1/n^2 from n=1 to infinity converge? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Confusing with harmonic series", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_159",
        description="Harmonic series divergence",
        prompt="Does the harmonic series 1 + 1/2 + 1/3 + 1/4 + ... converge? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Saying yes", "Not knowing it diverges"),
    ),
    ReasoningTask(
        task_id="reason_160",
        description="Telescoping sum value",
        prompt="What is the sum of 1/(n(n+1)) from n=1 to infinity? Answer as a decimal.",
        answer="1",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not recognizing telescoping", "Arithmetic error"),
    ),
    # More logic
    ReasoningTask(
        task_id="reason_161",
        description="Modus tollens",
        prompt="If P implies Q, and Q is false, can we conclude P is false? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Not recognizing modus tollens", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_162",
        description="Affirming consequent fallacy",
        prompt="If P implies Q, and Q is true, can we conclude P is true? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Affirming the consequent", "Saying yes"),
    ),
    ReasoningTask(
        task_id="reason_163",
        description="Denying antecedent fallacy",
        prompt="If P implies Q, and P is false, can we conclude Q is false? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Denying the antecedent", "Saying yes"),
    ),
    ReasoningTask(
        task_id="reason_164",
        description="Hypothetical syllogism",
        prompt="If P implies Q, and Q implies R, does P imply R? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Not recognizing transitivity", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_165",
        description="Disjunctive syllogism",
        prompt="If P or Q is true, and P is false, is Q true? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Not recognizing disjunctive syllogism", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_166",
        description="De Morgan's law verification",
        prompt="Is 'not (P and Q)' equivalent to '(not P) or (not Q)'? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not knowing De Morgan's", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_167",
        description="Distributive law",
        prompt="Is 'P and (Q or R)' equivalent to '(P and Q) or (P and R)'? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not knowing distributive law", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_168",
        description="Contrapositive equivalence",
        prompt="Is 'if P then Q' equivalent to 'if not Q then not P'? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Confusing with converse", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_169",
        description="Converse vs original",
        prompt="Is the converse of a true statement always true? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="easy",
        category="logic",
        common_errors=("Saying yes", "Not understanding converse"),
    ),
    ReasoningTask(
        task_id="reason_170",
        description="Biconditional check",
        prompt="Is 'P if and only if Q' equivalent to '(P implies Q) and (Q implies P)'? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not understanding biconditional", "Saying no"),
    ),
    # More combinatorics
    ReasoningTask(
        task_id="reason_171",
        description="Fibonacci and combinatorics",
        prompt="How many ways to climb n stairs taking 1 or 2 steps at a time, for n=7? Answer with just the number.",
        answer="21",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not recognizing Fibonacci pattern", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_172",
        description="Integer partition count",
        prompt="How many ways can the number 5 be written as a sum of positive integers (order doesn't matter)? Answer with just the number.",
        answer="7",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not counting all partitions", "Saying 6"),
    ),
    ReasoningTask(
        task_id="reason_173",
        description="Coin change ways",
        prompt="How many ways can you make 50 cents using quarters, dimes, nickels, and pennies? Answer with just the number.",
        answer="50",
        answer_type="int",
        difficulty="hard",
        category="combinatorics",
        common_errors=("Not using dynamic programming", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_174",
        description="Handshake problem",
        prompt="At a party with 10 people, everyone shakes hands with everyone else. How many handshakes occur? Answer with just the number.",
        answer="45",
        answer_type="int",
        difficulty="easy",
        category="combinatorics",
        common_errors=("Saying 100", "Not using C(10,2)"),
    ),
    ReasoningTask(
        task_id="reason_175",
        description="Committee selection",
        prompt="A committee of 3 is chosen from 5 men and 4 women. How many committees have exactly 2 men? Answer with just the number.",
        answer="30",
        answer_type="int",
        difficulty="medium",
        category="combinatorics",
        common_errors=("Not using C(5,2)*C(4,1)", "Arithmetic error"),
    ),
    # More sequences
    ReasoningTask(
        task_id="reason_176",
        description="Pell numbers",
        prompt="What is the next number in the sequence: 0, 1, 2, 5, 12, 29, ?",
        answer="70",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing Pell recurrence 2*P(n-1)+P(n-2)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_177",
        description="Jacobsthal numbers",
        prompt="What is the next number in the sequence: 0, 1, 1, 3, 5, 11, 21, ?",
        answer="43",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing J(n)=J(n-1)+2*J(n-2)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_178",
        description="Sylvester sequence",
        prompt="What is the next number in the sequence: 2, 3, 7, 43, ?",
        answer="1807",
        answer_type="int",
        difficulty="hard",
        category="sequence",
        common_errors=("Not recognizing s_n = s_1*...*s_{n-1} + 1", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_179",
        description="Power tower",
        prompt="What is 2^(2^(2^2))? Answer with just the number.",
        answer="65536",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not computing right-to-left", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_180",
        description="Graham sequence start",
        prompt="What is 3↑↑3 (3 tetrated to 3, i.e., 3^(3^3))? Answer with just the number.",
        answer="7625597484987",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not computing 3^27", "Arithmetic error"),
    ),
    # More applied math
    ReasoningTask(
        task_id="reason_181",
        description="Simple interest",
        prompt="If you borrow $5000 at 8% simple annual interest for 3 years, how much interest do you pay? Answer with just the number.",
        answer="1200",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Using compound interest", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_182",
        description="Discount calculation",
        prompt="An item costs $80 after a 20% discount. What was the original price? Answer with just the number.",
        answer="100",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Computing 80*1.2=96", "Not dividing by 0.8"),
    ),
    ReasoningTask(
        task_id="reason_183",
        description="Tax calculation",
        prompt="An item costs $50 plus 8% sales tax. What is the total cost? Answer with just the number.",
        answer="54",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Arithmetic error", "Not multiplying correctly"),
    ),
    ReasoningTask(
        task_id="reason_184",
        description="Profit percentage",
        prompt="An item is bought for $40 and sold for $50. What is the profit percentage? Answer with just the number.",
        answer="25",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Dividing by selling price instead of cost", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_185",
        description="Speed conversion",
        prompt="What is 60 mph in feet per second? Use 1 mile = 5280 feet. Answer with just the number (rounded to nearest integer).",
        answer="88",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not converting units properly", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_186",
        description="Temperature conversion",
        prompt="What is 100 degrees Celsius in Fahrenheit? Answer with just the number.",
        answer="212",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Using wrong formula", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_187",
        description="Density calculation",
        prompt="A block has mass 240g and volume 30cm^3. What is its density in g/cm^3? Answer with just the number.",
        answer="8",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not dividing mass by volume", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_188",
        description="Pressure calculation",
        prompt="A force of 100N is applied to an area of 0.5m^2. What is the pressure in Pascals? Answer with just the number.",
        answer="200",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not dividing force by area", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_189",
        description="Ohm's law",
        prompt="A circuit has 12V across a 4 ohm resistor. What is the current in amperes? Answer with just the number.",
        answer="3",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Not using V=IR", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_190",
        description="Kinetic energy",
        prompt="What is the kinetic energy of a 2kg object moving at 3 m/s? Answer with just the number (in Joules).",
        answer="9",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using 0.5*m*v^2", "Arithmetic error"),
    ),
    # More number theory
    ReasoningTask(
        task_id="reason_191",
        description="Fermat's last theorem",
        prompt="Does the equation a^n + b^n = c^n have positive integer solutions for n > 2? Answer 'yes' or 'no'.",
        answer="no",
        answer_type="string",
        difficulty="medium",
        category="logic",
        common_errors=("Not knowing Fermat's last theorem", "Saying yes"),
    ),
    ReasoningTask(
        task_id="reason_192",
        description="Twin prime check",
        prompt="Are 41 and 43 twin primes? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="math",
        common_errors=("Not checking both are prime with gap 2", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_193",
        description="Mersenne prime check",
        prompt="Is 2^7 - 1 = 127 a prime number? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="medium",
        category="math",
        common_errors=("Not checking primality", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_194",
        description="Fermat prime check",
        prompt="Is 2^(2^4) + 1 = 65537 a prime number? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="hard",
        category="math",
        common_errors=("Not checking primality", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_195",
        description="Goldbach decomposition",
        prompt="Express 10 as the sum of two primes. What is the larger prime? Answer with just the number.",
        answer="7",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Saying 5", "Not finding 3+7"),
    ),
    ReasoningTask(
        task_id="reason_196",
        description="GCD via Euclidean algorithm",
        prompt="What is the GCD of 48 and 18? Answer with just the number.",
        answer="6",
        answer_type="int",
        difficulty="medium",
        category="math",
        common_errors=("Not using Euclidean algorithm", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_197",
        description="LCM calculation",
        prompt="What is the LCM of 8 and 12? Answer with just the number.",
        answer="24",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Saying 4 (GCD instead)", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_198",
        description="Coprime check",
        prompt="Are 15 and 28 coprime? Answer 'yes' or 'no'.",
        answer="yes",
        answer_type="string",
        difficulty="easy",
        category="math",
        common_errors=("Not checking GCD=1", "Saying no"),
    ),
    ReasoningTask(
        task_id="reason_199",
        description="Prime factorization",
        prompt="What is the largest prime factor of 13195? Answer with just the number.",
        answer="29",
        answer_type="int",
        difficulty="hard",
        category="math",
        common_errors=("Not factoring completely", "Arithmetic error"),
    ),
    ReasoningTask(
        task_id="reason_200",
        description="Sum of primes below 10",
        prompt="What is the sum of all prime numbers below 10? Answer with just the number.",
        answer="17",
        answer_type="int",
        difficulty="easy",
        category="math",
        common_errors=("Including 1 as prime", "Missing a prime"),
    ),
]


def get_all_reasoning_tasks() -> list[ReasoningTask]:
    return REASONING_TASKS


def get_reasoning_task(task_id: str) -> ReasoningTask | None:
    for t in REASONING_TASKS:
        if t.task_id == task_id:
            return t
    return None


def check_answer(response: str, correct_answer: str, answer_type: str) -> bool:
    """Check if a response matches the correct answer."""
    response = response.strip().lower()
    correct = correct_answer.strip().lower()

    if answer_type == "int":
        try:
            return int(response) == int(correct)
        except ValueError:
            return False
    elif answer_type == "float":
        try:
            return abs(float(response) - float(correct)) < 0.01
        except ValueError:
            return False
    else:
        return response == correct


if __name__ == "__main__":
    print(f"Reasoning tasks: {len(REASONING_TASKS)}")
    by_cat = {}
    for t in REASONING_TASKS:
        by_cat.setdefault(t.category, []).append(t)
    for cat, tasks in sorted(by_cat.items()):
        print(f"  {cat}: {len(tasks)} tasks")
